export const demoFormState = {
  x1: "10",
  x2: "50",
  x3: "25",
  x41: "150",
  x42: "80",
  d1: "110",
  d2: "10",
  incomeWan: "4",
  saveWan: "1.5",
  incomeStability: "B",
  familyStructure: "B",
  parentSupport: "B",
  childrenStages: ["C"],
  insuranceStatus: "C",
  ageRange: "B",
  cityTier: "A",
  goals: ["A", "B", "D"],
  riskPreference: "A",
};
