import { labelMaps } from "@/lib/assessment/content";
import type { AssessmentInput } from "@/lib/assessment/schema";

/** Build the prompt that asks AI to do ALL computation and analysis. */
export function buildFullAnalysisPrompt(input: AssessmentInput): string {
  const labels = labelMaps;
  return [
    "你是一位持有 CFP 认证的资深家庭财务规划师。请根据以下原始数据，完成完整的家庭财务盘点。",
    "",
    "请按以下流程展示你的完整分析过程：",
    "",
    "第一步：计算关键指标（展示每一步计算公式和结果）",
    "- 总资产 = 各项资产之和",
    "- 总负债、负债率 = 总负债÷总资产×100%",
    "- 月支出 = 月收入-月结余",
    "- 应急金覆盖月数 = 活钱÷月支出",
    "- 储蓄率 = 月结余÷月收入×100%",
    "- 财富等级判断（<50万起步，50-200万起步家庭，200-600万中产，600-1000万富裕，>1000万高净值）",
    "- 压力测试：假设收入下降30%后的月结余",
    "",
    "第二步：诊断财务健康",
    "- 应急金是否充足（双职工稳定收入标准6个月，单职工或不稳定9-12个月）",
    "- 负债是否健康（优秀<30%，健康30-50%，警戒50-70%，危险>70%）",
    "- 保障是否完善",
    "- 房产占比是否合理（建议<60%）",
    "",
    "第三步：给出改善建议（每个建议具体到金额和时间节点）",
    "",
    "第四步：2026年资产配置建议（给出具体比例）",
    "",
    "原始数据：",
    `活钱（现金/余额宝等）：${input.x1} 万元`,
    `投资的钱（股票/基金/理财）：${input.x2} 万元`,
    `养老/公积金：${input.x3} 万元`,
    `自住房产：${input.x41} 万元`,
    `投资房产：${input.x42} 万元`,
    `房贷剩余：${input.d1} 万元`,
    `其他负债：${input.d2} 万元`,
    `家庭月收入：${input.incomeWan} 万元`,
    `家庭月结余：${input.saveWan} 万元`,
    `收入稳定性：${labels.incomeStability[input.incomeStability]}`,
    `家庭结构：${labels.familyStructure[input.familyStructure]}`,
    `父母赡养：${labels.parentSupport[input.parentSupport]}`,
    `子女情况：${input.childrenStages.length ? input.childrenStages.map((s) => labels.childrenStages[s]).join("、") : "暂无子女"}`,
    `保障状态：${labels.insuranceStatus[input.insuranceStatus]}`,
    `年龄段：${labels.ageRange[input.ageRange]}`,
    `城市级别：${labels.cityTier[input.cityTier]}`,
    `主要目标：${input.goals.map((g) => labels.goals[g]).join("、")}`,
    `风险偏好：${labels.riskPreference[input.riskPreference]}`,
    "",
    "写作要求：",
    "- 全程使用中文自然段落",
    "- 必须展示每一步的计算过程和公式",
    "- 不要使用 Markdown 格式（不要 # 号、不要 ** 加粗、不要 - 列表）",
    "- 语气专业但亲切，像面对面咨询",
    "- 总长度 800-1500 字",
  ].join("\n");
}
